name: 🎉 Release & Tag

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Bump version and tag
        run: |
          NEW_VERSION="v$(date +'%Y.%m.%d.%H%M')"
          echo "$NEW_VERSION" > VERSION

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git stash push -u
          git add VERSION

          if git diff --cached --quiet; then
            echo "🔹 Nothing to commit."
          else
            git commit -m "chore: release $NEW_VERSION"
            git push origin HEAD
            git tag "$NEW_VERSION"
            git push origin "$NEW_VERSION"
          fi

          git stash pop || true
